### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by ghost** [misiio/flutter_music_kit#4]
======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel plugins.misi.app/music_kit/music_subscription:
MissingPluginException(No implementation found for method listen on channel plugins.misi.app/music_kit/music_subscription)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:664:9)
<asynchronous suspension>
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel plugins.misi.app/music_kit/player_state:
MissingPluginException(No implementation found for method listen on channel plugins.misi.app/music_kit/player_state)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:664:9)
<asynchronous suspension>
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel plugins.misi.app/music_kit/player_queue:
MissingPluginException(No implementation found for method listen on channel plugins.misi.app/music_kit/player_queue)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:664:9)
<asynchronous suspension>
====================================================================================================

**Comment by wuschi** [comment]
Having the same problems here with version 1.3.0 on android. On IOS the plugin works fine. I modified the example app to initialize Music Kit with a developer and user token:

```dart
Future<void> initPlatformState() async {
    String? developerToken;
    String? userToken;

    if (Platform.isAndroid) {
      developerToken = "<developer Token>";
      userToken = "<user token>";
      await _musicKitPlugin.initialize(
          developerToken,
          musicUserToken: userToken);
    }
    final status = await _musicKitPlugin.authorizationStatus;

    switch (status) {
      case MusicAuthorizationStatusInitial() ||
      MusicAuthorizationStatusDenied() ||
      MusicAuthorizationStatusNotDetermined() ||
      MusicAuthorizationStatusRestricted():
        return;
      case MusicAuthorizationStatusAuthorized():
        {}
    }

    developerToken ??= await _musicKitPlugin.requestDeveloperToken();

    if (_musicSubsciption.canBecomeSubscriber == true) return;

    userToken ??= await _musicKitPlugin.requestUserToken(developerToken);

    final countryCode = await _musicKitPlugin.currentCountryCode;

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      _status = status;
      _developerToken = developerToken;
      _userToken = userToken!;
      _countryCode = countryCode;
    });
}
```

I cannot get the plugin to playback anything on Android. Does someone have a working example that I can try?

Maybe the following log output is of help:

```
D/SVAudioRendererNative( 8373): FootHillConfig::config() id: de4200d91db38376
W/AudioTrack( 8373): Use of stream types is deprecated for operations other than volume control
W/AudioTrack( 8373): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
W/lutions.hitsto( 8373): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
D/MusicKitPlugin( 8373): initialize() developerToken: 206 musicUserToken: 244

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel plugins.misi.app/music_kit/music_subscription:
MissingPluginException(No implementation found for method listen on channel plugins.misi.app/music_kit/music_subscription)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:368:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:715:11)
<asynchronous suspension>
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel plugins.misi.app/music_kit/player_state:
MissingPluginException(No implementation found for method listen on channel plugins.misi.app/music_kit/player_state)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:368:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:715:11)
<asynchronous suspension>
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel plugins.misi.app/music_kit/player_queue:
MissingPluginException(No implementation found for method listen on channel plugins.misi.app/music_kit/player_queue)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:368:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:715:11)
<asynchronous suspension>
====================================================================================================
```

**Comment by wuschi** [comment]
Output of `flutter doctor -v` for my project:

```
[✓] Flutter (Channel master, 3.31.0-1.0.pre.167, on macOS 15.3.2 24D81 darwin-arm64, locale de-DE) [1.900ms]
    • Flutter version 3.31.0-1.0.pre.167 on channel master at /Users/wuschi/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b6921e1895 (vor 7 Tagen), 2025-03-21 08:38:08 -0700
    • Engine revision b6921e1895
    • Dart version 3.8.0 (build 3.8.0-210.0.dev)
    • DevTools version 2.45.0-dev.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2,1s]
    • Android SDK at /Users/wuschi/Data/Applications/android-sdk-macosx/
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/wuschi/Data/Applications/android-sdk-macosx/
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [2,1s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [36ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [36ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2) [35ms]
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (5 available) [6,5s]
    • SM G960F (mobile)                         • 1c7b32b017037ece          • android-arm64  • Android 10 (API 29)
    • sdk gphone64 arm64 (mobile)               • emulator-5554             • android-arm64  • Android 16 (API 36) (emulator)
    • iPhone von Thomas (3) (wireless) (mobile) • 00008110-00090C261131801E • ios            • iOS 18.3.2 22D82
    • macOS (desktop)                           • macos                     • darwin-arm64   • macOS 15.3.2 24D81 darwin-arm64
    • Chrome (web)                              • chrome                    • web-javascript • Google Chrome 134.0.6998.166

[✓] Network resources [297ms]
    • All expected network resources are available.

• No issues found!
```

**Comment by sukhi-23** [comment]
Have you identified the issue?
