### ISSUE TITLE
Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported`

### ISSUE THREAD

**Issue by joachimsmit** [misiio/flutter_music_kit#8]
I keep getting this message: "Manifest merger failed : android:exported needs to be explicitly specified for element <activity#com.apple.android.sdk.authentication.SDKUriHandlerActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined." Can you provide an update?

**Comment by joachimsmit** [comment]
Problem solved. Cheers!

**Comment by joelathrop** [comment]
Hi @joachimsmit , I've been trying to use music_kit in a Flutter project, but keep getting this error:

```A problem occurred configuring project ':music_kit'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file.
```
   
You are the person who seemingly most recently had this package working. By any chance, did you run into this problem and/or do you know how to fix it? Thanks!

**Comment by joelathrop** [comment]
@joachimsmit If you happen to see this... I just got to the point where you originally posted. How did you fix that problem?

**Comment by joachimsmit** [comment]
Please contact me using my email address. joachimsmit@gmail.com. Download the music_kit plugin and use it localy.  In your project pubspec.yaml: dependencies:  music_kit: path: ../music_kit. In the build.gradle of the plugin 2 lines have to be changed. the implementation of the MusicKit libraries. use this instead: implementation 
 com.github.joachimsmit:musickitauth:1.1.3' implementation 'com.github.joachimsmit:mediaplayback:1.1.1'
Contact me with email. I will help you with further issues if you want me.

**Comment by joachimsmit** [comment]
@joelathrop Please contact me using my email address. oachimsmit@gmail.com. Download the music_kit plugin and use it localy. In your project pubspec.yaml: dependencies: music_kit: path: ../music_kit. In the build.gradle of the plugin 2 lines have to be changed. the implementation of the MusicKit libraries. use this instead: implementation
com.github.joachimsmit:musickitauth:1.1.3' implementation 'com.github.joachimsmit:mediaplayback:1.1.1'
Contact me with email. I will help you with further issues if you want me.

**Comment by stevesoltys** [comment]
@joelathrop https://github.com/misiio/flutter_music_kit/pull/9

**Comment by joelathrop** [comment]
@stevesoltys @joachimsmit Thanks for the fixes, those worked. Do you know why all of the methods are unimplemented in music_kit_platform_interface? How does anyone use this plugin if none of the methods work?

**Comment by stevesoltys** [comment]
@joelathrop the platform calls are made through flutter method channels: https://docs.flutter.dev/platform-integration/platform-channels

**Comment by stevesoltys** [comment]
https://github.com/misiio/flutter_music_kit/blob/master/music_kit_platform_interface%2Flib%2Fmethod_channel%2Fmethod_channel_music_kit.dart

**Comment by joelathrop** [comment]
@stevesoltys Getting this error. Could be my setup is incorrect

```E/flutter (12172): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method requestUserToken on channel plugins.misi.app/music_kit)
E/flutter (12172): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (12172): <asynchronous suspension>
E/flutter (12172): #1      MethodChannelMusicKit.requestUserToken (package:music_kit_platform_interface/method_channel/method_channel_music_kit.dart:64:9)
E/flutter (12172): <asynchronous suspension>
E/flutter (12172): #2      _SignInPageState.authenticateUser (package:threemoretime/main.dart:307:28)
E/flutter (12172): <asynchronous suspension>
```

**Comment by stevesoltys** [comment]
There are only implementations for iOS and Android (not web, if you're trying there). You should be able to directly depend on my fork without using your own local fork and it should run correctly on iOS and Android.

**Comment by stevesoltys** [comment]
```yaml
  music_kit:
    git:
      url: https://github.com/stevesoltys/flutter_music_kit.git
      path: music_kit
      ref: f6d920688b16668e3300f939ee07a3a939cd987c
```

**Comment by joelathrop** [comment]
@stevesoltys I'm working with Flutter on Android Studio. Still getting this error:
```MissingPluginException(No implementation found for method initialize on channel plugins.misi.app/music_kit)```
For every MusicKit instance method I try to call.

**Comment by joachimsmit** [comment]
Do you have a developer token? That is the hardest part. Once you have
that, the rest is a piece of cake.

**Comment by xavier-lyu** [comment]
fixed in #9 by @stevesoltys , thx
